--
-- CREATE TABLES
--

-- CREATE TABLE BUSINESS

CREATE TABLE BUSINESS (
  BUSINESS_ID  VARCHAR2(1000),
  ADDRESS VARCHAR2(1000),
  HOURS VARCHAR2(1000),
  OPEN_CLOSE VARCHAR2(1000),
  CATEGORIES VARCHAR2(5000),
  REVIEW_COUNT NUMBER(8,2),
  CITY VARCHAR2(1000),
  STATE1 VARCHAR2(1000),
  LATITUDE NUMBER(8,2),
  LONGITUDE NUMBER(8,2),
  BUSINESS_NAME VARCHAR2(1000),
  NEIGHBOURS VARCHAR2(1000),
  STARS NUMBER(8,2),
  ATTRIBUTES1 VARCHAR2(10000),
  TYPE1 VARCHAR2(1000),
  CONSTRAINT BUSINESS_pk PRIMARY KEY (BUSINESS_ID) 
);

----------------------------------------------------------------------------------------------------------------

-- CREATE TABLE BUSINESS_CATEGORY

CREATE TABLE BUSINESS_CATEGORY (
  BUSINESS_ID VARCHAR2(1000),
  BUS_CATG_ID VARCHAR2(1000),
  BUS_CATG_NAME VARCHAR2(10000),
  CONSTRAINT fk_BUSINESSREF FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

----------------------------------------------------------------------------------------------------------------

-- CREATE TABLE YELP_USER

CREATE TABLE YELP_USER (
YELPING_SINCE VARCHAR2(100),
TOTAL_VOTES NUMBER(8,2),
REVIEW_COUNT NUMBER(8,2),
FIRST_NAME VARCHAR2(10000),
YELP_ID VARCHAR2(2000) PRIMARY KEY,
FRIEND_LIST VARCHAR(10000),
FANS NUMBER(8,2),
AVERAGE_STARS DECIMAL(19, 4),
TYPE1 VARCHAR2(10000),
COMPLIMENT_LIST VARCHAR2(20000),
ELITE VARCHAR2(10000)
);

----------------------------------------------------------------------------------------------------------------

-- CREATE TABLE REVIEWS

CREATE TABLE REVIEWS (
TOTAL_VOTES NUMBER(8,2),
USER_ID VARCHAR(1000) NOT NULL,
REVIEW_ID VARCHAR(1000) PRIMARY KEY,
STARS NUMBER(8,2),
TYPE1 VARCHAR2(10000),
TEXT1 VARCHAR2(10000),
TEXT2 VARCHAR2(30000),
BUSINESS_ID  VARCHAR(1000) NOT NULL,
PUBLISH_DATE VARCHAR2(2000),
CONSTRAINT fk_BUSINESS_REF FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID),
CONSTRAINT fk_USERREF FOREIGN KEY (USER_ID) REFERENCES YELP_USER(YELP_ID)
);

----------------------------------------------------------------------------------------------------------------

-- CREATE TABLE BUSINESSATTRIBUTES

CREATE TABLE BUSINESSATTRIBUTES(
BUSINESS_ID VARCHAR2(1000),
BUS_ATTRIBUTE VARCHAR2(10000),
is_active varchar2(5),
CONSTRAINT fk_ATTRIBUTEREF FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

----------------------------------------------------------------------------------------------------------------

-- CREATE TABLE CHECKIN_INFO

CREATE TABLE CHECKIN_INFO (
BUSINESS_ID VARCHAR2(1000) NOT NULL,
CHECKIN_DATE NUMBER,
NUMBER_CHECKIN NUMBER,
CONSTRAINT fk_CHECKINREF FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

----------------------------------------------------------------------------------------------------------------

--CREATE TABLE CHECKIN

CREATE TABLE CHECKIN (
BUSINESS_ID VARCHAR2(1000) NOT NULL,
TYPE1 VARCHAR2(1000),
CHECKIN_INFO VARCHAR2(10000)
);

----------------------------------------------------------------------------------------------------------------

COMMIT;